image: registry.gitlab.com/sosy-lab/teaching/sep-template-group-project:latest

variables:
  OUTPUT_PATH: "out"
  LIB_PATH: "lib"

stages:
  - build
  - test
  - execute

build:
  stage: build
  image: maven:latest
  script:
    #- find $LIB_PATH -iname "*.jar" | tr '\n' ':' > libraries.txt
    #- find -name "*.java" > sources.txt
    #- cat sources.txt
    #- mkdir $OUTPUT_PATH
    #- javac -d $OUTPUT_PATH -Xlint:all -Werror -g -cp "$CLASSPATH:$(cat libraries.txt)" @sources.txt
  - 'mvn package'
  artifacts:
    paths:
    # Keep compiled java files and list of files
      #- $OUTPUT_PATH
      #- sources.txt
      #- libraries.txt
      - target/classes
      - maven

spotbugs:
  stage: test
  image: maven:latest
  script:
   # - spotbugs -auxclasspath "$CLASSPATH:$(cat libraries.txt)" -textui -longBugCodes -effort:max -exitcode $OUTPUT_PATH
    - 'mvn spotbugs:spotbugs'

checkstyle:
  stage: test
  image: maven:latest
  script:
    #- java -jar /opt/checkstyle-10.3-all.jar -c /opt/google_checks.xml @sources.txt
    - 'mvn checkstyle:check'

unit-tests:
  stage: test
  image: maven:latest
  script:
    #- java -jar $JUNIT5_PATH --class-path "$OUTPUT_PATH:$(cat libraries.txt)" --scan-class-path
    - 'mvn test'

execute:
  stage: execute
  image: maven:latest
  script:
    # SEP Teams: adjust the next line for your project
    #-  java -cp "$OUTPUT_PATH:$(cat libraries.txt)" de.lmu.ifi.sosylab.AzulMain
#  - mvn test
  - mvn exec:java
  - mvn clean
